export const pokemonTypecolor: { name: string, color: string }[] = [
    { name: "bug", color: "#A7B723" },
    { name: "dark", color: "#75574C" },
    { name: "dragon", color: "#7037ff" },
    { name: "electric", color: "#f9cf30" },
    { name: "fairy", color: "#e69eac" },
    { name: "fighring", color: "#C12239" },
    { name: "fire", color: "#F57D31" },
    { name: "flying", color: "#A891EC" },
    { name: "ghost", color: "#70559B" },
    { name: "normal", color: "#AAA67F" },
    { name: "grass", color: "#74CB48" },
    { name: "ground", color: "#DEC16B" },
    { name: "ice", color: "#9AD6DF" },
    { name: "poison", color: "#A43E9E" },
    { name: "psychic", color: "#B69E31" },
    { name: "rock", color: "#FB5584" },
    { name: "steel", color: "#B7B9D0" },
    { name: "water", color: "#6493EB" },
];
